// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0ainGC0dDHr0cISuCfPvliPnLOp9rxCg',
    appId: '1:990782984427:web:25a9c197964cb44bdbeeae',
    messagingSenderId: '990782984427',
    projectId: 'road-to-fitness-dev',
    authDomain: 'road-to-fitness-dev.firebaseapp.com',
    storageBucket: 'road-to-fitness-dev.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHvrvHzj84t_QBgWIdL_2KYxLIeBqvAgI',
    appId: '1:990782984427:android:22011c106c6e767cdbeeae',
    messagingSenderId: '990782984427',
    projectId: 'road-to-fitness-dev',
    storageBucket: 'road-to-fitness-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLSBP2H3tWo5-S-reMT4zW6Sq5NXuEBkk',
    appId: '1:990782984427:ios:98017f45399492f4dbeeae',
    messagingSenderId: '990782984427',
    projectId: 'road-to-fitness-dev',
    storageBucket: 'road-to-fitness-dev.appspot.com',
    iosClientId: '990782984427-aqlkfq6dvenbckohvmmguhjrrvma64ji.apps.googleusercontent.com',
    iosBundleId: 'com.example.fitnessAppRiverpod',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLSBP2H3tWo5-S-reMT4zW6Sq5NXuEBkk',
    appId: '1:990782984427:ios:98017f45399492f4dbeeae',
    messagingSenderId: '990782984427',
    projectId: 'road-to-fitness-dev',
    storageBucket: 'road-to-fitness-dev.appspot.com',
    iosClientId: '990782984427-aqlkfq6dvenbckohvmmguhjrrvma64ji.apps.googleusercontent.com',
    iosBundleId: 'com.example.fitnessAppRiverpod',
  );
}
